#!/usr/bin/env bash

set -e
set -x

run-test ()
{
  diff fixtures/output <( src/$1/bin/mower "$(cat fixtures/input)") > /dev/null 2>&1
  error=$?
  if [ $error -eq 0 ]
  then
    echo -e "\e[32mvalid output\e[0m"
  fi
}

run-test 'python'
run-test 'ruby'
